# Generated by Django 5.1 on 2024-08-29 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('litreview_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='author',
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
